version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app_dockerfile
        container_name: migration-app
        restart: unless-stopped
        tty: true
        working_dir: /app
        volumes:
            - ./app:/app
            - ./data/samples/:/data
        ports:
            - 6780:5000
        networks:
            - migration

    web:
        build:
            context: .
            dockerfile: ./docker/web_dockerfile
        container_name: migration-web
        volumes:
            - ./web/:/var/www/html
        ports:
            - "6781:80"
        networks:
            - migration
        depends_on:
            - db      

    db:
        container_name: 'migration-db'
        image: mysql:8.0.29
        restart: unless-stopped
        tty: true
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--innodb-buffer-pool-size=1G"
            - "--innodb-buffer-pool-instances=2"
        environment:
            MYSQL_DATABASE: db_migration
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            TZ: 'Asia/Dhaka'
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/temp:/dumbs
            - ./docker/mysql.cnf:/etc/mysql/my.cnf
        ports:
            - "6782:3306"
        networks:
            - migration
      
    phpmyadmin:
        container_name: 'migration-phpmyadmin'
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - "6783:80"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'root'
            PMA_ARBITRARY: 1
        networks:
            - migration
        depends_on:
            - db

networks:
    migration:
        driver: bridge
volumes:
    data:
        driver: local
